# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'trial 3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for trial 3
	pod 'Firebase'
    	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'GoogleSignIn'
end
